---
plugins:
  time:
    url: oci://ghcr.io/tuananh/time-plugin:latest
  qr-code:
    url: oci://ghcr.io/tuananh/qrcode-plugin:latest
  hash:
    url: oci://ghcr.io/tuananh/hash-plugin:latest
  myip:
    url: oci://ghcr.io/tuananh/myip-plugin:latest
    runtime_config:
      allowed_hosts:
        - "1.1.1.1"
  fetch:
    url: oci://ghcr.io/tuananh/fetch-plugin:latest
    runtime_config:
      allowed_hosts:
        - "*"
